version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/rbt-next" # Location of package manifests
      schedule:
          interval: "weekly"

    - package-ecosystem: "npm"
      directory: "/rbt-next-paginator" # Location of package manifests
      schedule:
          interval: "weekly"

    - package-ecosystem: "npm"
      directory: "/rbt-next-toolkit" # Location of package manifests
      schedule:
          interval: "weekly"